// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM0quciJkV44AqZVG_CKOoQ4T4V-PIi0U',
    appId: '1:611935945594:web:980262986175a1cb50ccc3',
    messagingSenderId: '611935945594',
    projectId: 'eduquest-a2922',
    authDomain: 'eduquest-a2922.firebaseapp.com',
    storageBucket: 'eduquest-a2922.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClhtPNkxz0gGzqMztC6-YATPHSKd6znUU',
    appId: '1:611935945594:android:c9daeb0b88a9234f50ccc3',
    messagingSenderId: '611935945594',
    projectId: 'eduquest-a2922',
    storageBucket: 'eduquest-a2922.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW_xGR0CqWrEU33c1jNbDg45_nBSfA7BQ',
    appId: '1:611935945594:ios:4e632406a95ae04f50ccc3',
    messagingSenderId: '611935945594',
    projectId: 'eduquest-a2922',
    storageBucket: 'eduquest-a2922.firebasestorage.app',
    iosBundleId: 'com.example.flutterPomodoro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW_xGR0CqWrEU33c1jNbDg45_nBSfA7BQ',
    appId: '1:611935945594:ios:4e632406a95ae04f50ccc3',
    messagingSenderId: '611935945594',
    projectId: 'eduquest-a2922',
    storageBucket: 'eduquest-a2922.firebasestorage.app',
    iosBundleId: 'com.example.flutterPomodoro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBM0quciJkV44AqZVG_CKOoQ4T4V-PIi0U',
    appId: '1:611935945594:web:278fbc5a52676d8b50ccc3',
    messagingSenderId: '611935945594',
    projectId: 'eduquest-a2922',
    authDomain: 'eduquest-a2922.firebaseapp.com',
    storageBucket: 'eduquest-a2922.firebasestorage.app',
  );

}