// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:flutter_pomodoro/models/quiz_question.dart';
import 'package:flutter_pomodoro/models/quiz_session.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(QuizQuestionHiveAdapter());
    registerAdapter(QuizSessionAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(QuizQuestionHiveAdapter());
    registerAdapter(QuizSessionAdapter());
  }
}
